name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x86, amd64]
        include:
          - platform: x86
            artifact_suffix: _x86
            qt_arch: win32_msvc2019
          - platform: amd64
            inno_args: /DBUILD64
            qt_arch: win64_msvc2019_64
    steps:
      - uses: actions/checkout@v2
      - uses: jurplel/install-qt-action@v2.13.0
        with:
          arch: ${{ matrix.qt_arch }}
      - name: Build
        shell: cmd
        run: |
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.platform }}
          qmake OpenRCT2Launcher.pro
          nmake
      - name: Prepare artifacts
        run: |
          mkdir artifacts
          copy release\OpenRCT2.exe artifacts
          windeployqt artifacts\OpenRCT2.exe
          #copy libeay32.dll artifacts
          #copy ssleay32.dll artifacts
          7z a OpenRCT2Launcher-${{ runner.os }}${{ matrix.artifact_suffix }}.zip 
          iscc ${{ matrix.inno_args }} installer.iss
      - name: Upload artifact (zip)
        uses: actions/upload-artifact@v2
        with:
          name: OpenRCT2Launcher-${{ runner.os }}${{ matrix.artifact_suffix }}
          path: OpenRCT2Launcher*.zip
          if-no-files-found: error
      - name: Upload artifact (exe)
        uses: actions/upload-artifact@v2
        with:
          name: OpenRCT2Launcher-${{ runner.os }}${{ matrix.artifact_suffix }}
          path: OpenRCT2Launcher*.exe
          if-no-files-found: error
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jurplel/install-qt-action@v2.13.0
      - name: qmake
        run: qmake OpenRCT2Launcher.pro
      - name: Build
        run: make -j$(nproc)
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jurplel/install-qt-action@v2.13.0
      - name: qmake
        run: qmake OpenRCT2Launcher.pro
      - name: Build
        run: make -j$(sysctl -n hw.availcpu)
